In [10]:
import pandas as pd

trip_path = "../data/raw/trips/yellow_tripdata_2026-07.parquet"
zone_path = "../data/raw/zones/taxi_zone_lookup.csv"

trips = pd.read_parquet(trip_path)
zones = pd.read_csv(zone_path)

print("Trips shape:", trips.shape)
print("Zones shape:", zones.shape)

Trips shape: (3530109, 21)
Zones shape: (265, 4)

In [11]:
print("TRIP COLUMNS")
print(trips.columns.tolist())

print("\nZONE COLUMNS")
print(zones.columns.tolist())

TRIP COLUMNS
['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'Airport_fee', 'cbd_congestion_fee', 'request_source']

ZONE COLUMNS
['LocationID', 'Borough', 'Zone', 'service_zone']

In [12]:
trips.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,request_source
0,1,2026-07-01 00:36:25,2026-07-01 00:43:18,1.0,2.00,1.0,N,138,138,2,...,8.00,0.5,0.00,0.00,1.0,19.50,0.0,2.0,0.00,NaN
1,1,2026-07-01 00:02:53,2026-07-01 00:17:12,1.0,3.20,1.0,N,162,112,2,...,4.25,0.5,0.00,0.00,1.0,21.35,2.5,0.0,0.75,NaN
2,2,2026-07-01 00:18:56,2026-07-01 00:27:38,1.0,3.18,1.0,N,137,263,1,...,1.00,0.5,4.81,0.00,1.0,24.06,2.5,0.0,0.75,NaN
3,1,2026-07-01 00:35:06,2026-07-01 00:57:51,0.0,10.00,1.0,N,138,246,1,...,11.25,0.5,12.30,7.46,1.0,74.01,2.5,2.0,0.75,NaN
4,7,2026-07-01 00:36:59,2026-07-01 00:36:59,2.0,9.62,1.0,N,140,106,1,...,0.00,0.5,9.59,0.00,1.0,57.54,2.5,0.0,0.75,NaN

In [13]:
zones.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [14]:
print(trips.dtypes)

VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag                  str
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
cbd_congestion_fee              float64
request_source                      str
dtype: object

In [15]:
print(zones.dtypes)

LocationID      int64
Borough           str
Zone              str
service_zone      str
dtype: object

In [16]:
from pathlib import Path

trip_path = Path("../data/raw/trips/yellow_tripdata_2026-07.parquet")
zone_path = Path("../data/raw/zones/taxi_zone_lookup.csv")

print("Trip file exists:", trip_path.exists())
print("Zone file exists:", zone_path.exists())

print("\nTrip file size:", round(trip_path.stat().st_size / (1024 * 1024), 2), "MB")
print("Zone file size:", round(zone_path.stat().st_size / 1024, 2), "KB")

Trip file exists: True
Zone file exists: True

Trip file size: 58.83 MB
Zone file size: 12.04 KB

In [17]:
print("Trip records loaded:", len(trips))
print("Zone records loaded:", len(zones))

print("Trip columns:", len(trips.columns))
print("Zone columns:", len(zones.columns))

Trip records loaded: 3530109
Zone records loaded: 265
Trip columns: 21
Zone columns: 4

To get the idea if the data is only of July 2026,

In [18]:
print("Minimum pickup:", trips["tpep_pickup_datetime"].min())
print("Maximum pickup:", trips["tpep_pickup_datetime"].max())

Minimum pickup: 2008-12-30 23:06:00
Maximum pickup: 2026-08-05 20:54:00

In [19]:
print("Minimum dropoff:", trips["tpep_dropoff_datetime"].min())
print("Maximum dropoff:", trips["tpep_dropoff_datetime"].max())

Minimum dropoff: 2008-12-30 23:15:45
Maximum dropoff: 2026-08-05 21:04:08

In [20]:
year_month_distribution = (
    trips["tpep_pickup_datetime"]
    .dt.to_period("M")
    .value_counts()
    .sort_index()
)

print(year_month_distribution)

tpep_pickup_datetime
2008-12          1
2026-06          7
2026-07    3530063
2026-08         38
Freq: M, Name: count, dtype: int64

In [21]:
july_2026_trips = trips[
    trips["tpep_pickup_datetime"].dt.to_period("M") == "2026-07"
].copy()
print("July 2026 rows:", len(july_2026_trips))

July 2026 rows: 3530063

Verification

In [22]:
print(
    "July 2026 minimum pickup:",
    july_2026_trips["tpep_pickup_datetime"].min()
)

print(
    "July 2026 maximum pickup:",
    july_2026_trips["tpep_pickup_datetime"].max()
)

July 2026 minimum pickup: 2026-07-01 00:00:00
July 2026 maximum pickup: 2026-07-31 23:59:59

In [23]:
print(
    "July-filtered minimum dropoff:",
    july_2026_trips["tpep_dropoff_datetime"].min()
)

print(
    "July-filtered maximum dropoff:",
    july_2026_trips["tpep_dropoff_datetime"].max()
)

July-filtered minimum dropoff: 2026-07-01 00:00:15
July-filtered maximum dropoff: 2026-08-01 21:49:34

In [24]:
print(
    trips[
        trips["tpep_pickup_datetime"].dt.year < 2020
    ][
        [
            "tpep_pickup_datetime",
            "tpep_dropoff_datetime",
            "PULocationID",
            "DOLocationID",
            "trip_distance"
        ]
    ].head(20)
)

        tpep_pickup_datetime tpep_dropoff_datetime  PULocationID  \
2176020  2008-12-30 23:06:00   2008-12-30 23:15:45            43

         DOLocationID  trip_distance
2176020           141           1.65

## 4B — Retrieval Validation

### 4B.1 Required Trip Columns

The retrieved trip dataset must contain the fields required to answer
the defined business questions and connect trip records to the taxi
zone reference data.

In [25]:
required_trip_columns = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime",
    "PULocationID",
    "DOLocationID",
    "trip_distance"
]

missing_trip_columns = [
    col for col in required_trip_columns
    if col not in trips.columns
]

print("Required columns:", required_trip_columns)
print("Missing columns:", missing_trip_columns)

if missing_trip_columns:
    print("❌ Retrieval validation failed")
else:
    print("✅ All required trip columns are present")

Required columns: ['tpep_pickup_datetime', 'tpep_dropoff_datetime', 'PULocationID', 'DOLocationID', 'trip_distance']
Missing columns: []
✅ All required trip columns are present

In [26]:
reporting_start = pd.Timestamp("2026-07-01 00:00:00")
reporting_end = pd.Timestamp("2026-07-31 23:59:59")

july_pickups = july_2026_trips["tpep_pickup_datetime"]

print("Reporting start:", reporting_start)
print("Reporting end:", reporting_end)

print("Actual minimum pickup:", july_pickups.min())
print("Actual maximum pickup:", july_pickups.max())

print(
    "All pickups within reporting period:",
    july_pickups.between(reporting_start, reporting_end).all()
)

Reporting start: 2026-07-01 00:00:00
Reporting end: 2026-07-31 23:59:59
Actual minimum pickup: 2026-07-01 00:00:00
Actual maximum pickup: 2026-07-31 23:59:59
All pickups within reporting period: True

In [27]:
print("Zone rows:", len(zones))
print("Zone columns:")
print(zones.columns.tolist())

print("\nDuplicate LocationIDs:")
print(zones["LocationID"].duplicated().sum())

print("\nMissing LocationIDs:")
print(zones["LocationID"].isna().sum())

Zone rows: 265
Zone columns:
['LocationID', 'Borough', 'Zone', 'service_zone']

Duplicate LocationIDs:
0

Missing LocationIDs:
0

In [28]:
zone_ids = set(zones["LocationID"].dropna())

pickup_location_ids = set(
    july_2026_trips["PULocationID"].dropna()
)

dropoff_location_ids = set(
    july_2026_trips["DOLocationID"].dropna()
)

unmatched_pickup_ids = pickup_location_ids - zone_ids
unmatched_dropoff_ids = dropoff_location_ids - zone_ids

print("Unique pickup location IDs:", len(pickup_location_ids))
print("Unique dropoff location IDs:", len(dropoff_location_ids))

print("Unmatched pickup IDs:", len(unmatched_pickup_ids))
print("Unmatched dropoff IDs:", len(unmatched_dropoff_ids))

print("Sample unmatched pickup IDs:", sorted(unmatched_pickup_ids)[:20])
print("Sample unmatched dropoff IDs:", sorted(unmatched_dropoff_ids)[:20])

Unique pickup location IDs: 260
Unique dropoff location IDs: 261
Unmatched pickup IDs: 0
Unmatched dropoff IDs: 0
Sample unmatched pickup IDs: []
Sample unmatched dropoff IDs: []

In [29]:
print("========== RETRIEVAL SUMMARY ==========")

print("Raw trip rows:", len(trips))
print("July 2026 trip rows:", len(july_2026_trips))
print("Zone reference rows:", len(zones))

print(
    "July pickup range:",
    july_2026_trips["tpep_pickup_datetime"].min(),
    "→",
    july_2026_trips["tpep_pickup_datetime"].max()
)

print(
    "July trip columns available:",
    len(july_2026_trips.columns)
)

print("========================================")

========== RETRIEVAL SUMMARY ==========
Raw trip rows: 3530109
July 2026 trip rows: 3530063
Zone reference rows: 265
July pickup range: 2026-07-01 00:00:00 → 2026-07-31 23:59:59
July trip columns available: 21
========================================

## Retrieval Mode 2 — SQL retrieval

We'll use DuckDB because it can query Parquet and CSV directly without requiring us to build a complicated database first.

Parquet + CSV
     │
     ▼
   DuckDB
     │
     ▼
    SQL
     │
     ├── count trips
     ├── filter July 2026
     └── inspect zone relationship

In [30]:
import duckdb

con = duckdb.connect()

In [31]:
sql_trip_count = con.execute("""
    SELECT COUNT(*) AS trip_count
    FROM read_parquet('../data/raw/trips/yellow_tripdata_2026-07.parquet')
""").fetchdf()

print(sql_trip_count)

   trip_count
0     3530109

In [32]:
sql_july = con.execute("""
    SELECT *
    FROM read_parquet('../data/raw/trips/yellow_tripdata_2026-07.parquet')
    WHERE tpep_pickup_datetime >= '2026-07-01'
      AND tpep_pickup_datetime < '2026-08-01'
""").fetchdf()

print("SQL July rows:", len(sql_july))

SQL July rows: 3530063

In [33]:
print("Pandas July rows:", len(july_2026_trips))
print("SQL July rows:", len(sql_july))

print(
    "Counts match:",
    len(july_2026_trips) == len(sql_july)
)

Pandas July rows: 3530063
SQL July rows: 3530063
Counts match: True

In [34]:
sql_zones = con.execute("""
    SELECT *
    FROM read_csv_auto('../data/raw/zones/taxi_zone_lookup.csv')
""").fetchdf()

print("SQL zone rows:", len(sql_zones))
print(sql_zones.head())

SQL zone rows: 265
   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [35]:
print(
    "Zone counts match:",
    len(sql_zones) == len(zones)
)

Zone counts match: True

In [37]:
sql_zone_activity = con.execute("""
    SELECT
        t.PULocationID,
        z.Borough,
        z.Zone,
        COUNT(*) AS trip_count
    FROM read_parquet(
        '../data/raw/trips/yellow_tripdata_2026-07.parquet'
    ) t
    LEFT JOIN read_csv_auto(
        '../data/raw/zones/taxi_zone_lookup.csv'
    ) z
        ON t.PULocationID = z.LocationID
    WHERE t.tpep_pickup_datetime >= '2026-07-01'
      AND t.tpep_pickup_datetime < '2026-08-01'
    GROUP BY
        t.PULocationID,
        z.Borough,
        z.Zone
    ORDER BY trip_count DESC
    LIMIT 10
""").fetchdf()

print(sql_zone_activity)

   PULocationID    Borough                          Zone  trip_count
0           161  Manhattan                Midtown Center      152733
1           132     Queens                   JFK Airport      151816
2           237  Manhattan         Upper East Side South      140423
3           236  Manhattan         Upper East Side North      118463
4           186  Manhattan  Penn Station/Madison Sq West      117790
5           162  Manhattan                  Midtown East      113562
6           230  Manhattan     Times Sq/Theatre District      108789
7           170  Manhattan                   Murray Hill       97766
8           142  Manhattan           Lincoln Square East       97599
9            68  Manhattan                  East Chelsea       96828